config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # Database admin route
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  # Authentication route
  devise_for :users

  # Home and user show
  root to: 'pages#home'
  resources :pages, only: %i[index show edit update]

  # Request pages
  resources :requests, except: :destroy
  # Update requests
  patch 'requests/get/:id', to: 'requests#get', as: :request_get
  # Solve requests
  patch 'requests/conclude/:id', to: 'requests#conclude', as: :request_conclude

  # Redirect to index page on successful sign in
  get '/user' => "pages#index", :as => :user_root

  # Blazer dashboard pages
  authenticate :user, ->(user) { user.admin? || user.role == 'manager' } do
    mount Blazer::Engine, at: "blazer"
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/request.rb
class Request < ApplicationRecord
  INSTRUMENTS = %w[Medidor\ de\ Energia\ Elétrica Medidor\ de\ Água Medidor\ de\ Gás].freeze
  SERVICES = %w[Verificação Perícia].freeze
  STATES = %w[Acre Alagoas Amapá Amazonas Bahia Ceará Distrito\ Federal Espírito\ Santo Goiás Maranhão Mato\ Grosso
              Mato\ Grosso\ do\ Sul Minas\ Gerais Pará Paraíba Paraná Pernambuco Piauí Rio\ de\ Janeiro
              Rio\ Grande\ do\ Norte Rio\ Grande\ do\ Sul Rondônia Santa\ Catarina São\ Paulo Sergipe Tocantins].freeze
  STATUS = %w[Aberta Em\ andamento Realizada].freeze
  belongs_to :citizen, class_name: 'User'
  belongs_to :tech, optional: true, class_name: 'User'
  validates :instrument, :service, :location, :description, presence: true

  include PgSearch::Model
  pg_search_scope :search_by_description,
                  against: :description,
                  using: { tsearch: { prefix: true } }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :citizen_requests, class_name: 'Request', foreign_key: 'citizen_id'
  has_many :tech_requests, class_name: 'Request', foreign_key: 'tech_id'

  validates :full_name, presence: true
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  include Pundit

  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  def user_not_authorized
    flash[:alert] = "Você não está autorizado a realizar este acesso."
    redirect_to(requests_path)
  end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  before_action :set_user, only: %i[show edit update]

  def home
  end

  def index
  end

  def show; end

  def edit; end

  def update
    if @user.update(user_params)
      redirect_to page_path(@user), notice: 'Seus dados foram atualizados com sucesso.'
    else
      render :edit
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
    authorize @user
  end

  def user_params
    params.require(:user).permit(:full_name, :phone_number, :address)
  end
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  before_action :set_request, only: %i[get conclude show edit update]

  def index
    case current_user.role
    when "manager"
      @requests = requests_for_manager
      render action: "index_manager" and return
    when "tech"
      @requests = policy_scope(Request.where(tech: nil, location: current_user.location)
                  .or(Request.where(tech: current_user, location: current_user.location)))
                  .order(:created_at)
    when "citizen"
      @requests = policy_scope(Request.where(citizen: current_user)).order(:created_at)
    end
  end

  def show
    # set_request - Substituido pelo before_action
  end

  def new
    @request = Request.new
    authorize @request
  end

  def create
    # Cria um novo request
    @request = Request.new(request_params)
    @request.citizen = current_user
    authorize @request
    if @request.save
      redirect_to request_path(@request), notice: 'Solicitação criada com sucesso!'
    else
      render :new
    end
  end

  def edit
    # set_request - Substituido pelo before_action
  end

  def update
    # set_request - Substituido pelo before_action
    @request.update(tech: nil) if request_params["status"].eql?("Aberta")
    if @request.update(request_params) # && !@request.report.blank?
      redirect_to request_path(@request), notice: 'Solicitação atualizada com sucesso!'
    else
      #redirect_to edit_request_path(@request), alert: 'Relatório necessita ser preenchido'
      render :edit
    end
  end

  def get
    # set_request - Substituido pelo before_action
    @request.update(tech: current_user, status: "Em andamento")
    redirect_to @request, notice: 'Atribuição realizada com sucesso!'
  end

  def conclude
    # set_request - Substituido pelo before_action
    @request.update(status: "Realizada")
    redirect_to requests_path
  end

  private

  def requests_for_manager
    if params[:query].blank?
      requests = policy_scope(Request.order(:created_at))
    elsif params[:button]
      # busca pelo termo especificado pelo usuario e presente no campo description
      requests = policy_scope(Request).search_by_description(params[:query]).order(:created_at)
    else
      # busca pelos filtros pré estabelecidos: Abertas, Em Andamento, Realizadas, Todas
      requests = policy_scope(Request).where(status: params[:query]).order(:created_at)
    end
    return requests
  end

  def set_request
    @request = Request.find(params[:id])
    authorize @request
  end

  def request_params
    params.require(:request).permit(:instrument, :service, :location, :status, :description, :report)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Verifica Inmetro</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= favicon_link_tag %>

    <!-- Dsgov CSS -->
    <link rel="stylesheet" href="https://dsgov.estaleiro.serpro.gov.br/assets/design-system/dist/dsgov.css">
    <!-- Fonte Rawline-->
    <link rel="stylesheet" href="https://cdn.dsgovserprodesign.estaleiro.serpro.gov.br/design-system/fonts/rawline/css/rawline.css"/>
    <!-- Fonte Raleway-->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway:300,400,500,600,700,800,900&amp;display=swap"/>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <% unless action_name == 'home' %>
      <%= render 'shared/navbar' %>
    <% end %>

    <%= render 'shared/flashes' %>

    <%= yield %>

    <%= render 'shared/footer' %>

    <!-- Dsgov scripts -->
    <%= javascript_include_tag "https://dsgov.estaleiro.serpro.gov.br/assets/design-system/dist/dsgov.min.js" %>
  </body>
</html>

app/views/pages/_form.html.erb
<div class='container'>
  <%#= simple_form_for(@user, url: page_path(@user), html: { method: :put }) do |f| %>
  <%= simple_form_for(@user, url: page_path(@user)) do |f| %>
    <%= f.input :full_name, label: "Nome", input_html: { class: "fit-content" } %>
    <%= f.input :phone_number, input_html: { class: "fit-content" } %>
    <%= f.input :address %>

    <div class="d-flex justify-content-end mb-3">
      <%= link_to 'Voltar', page_path(@user), class: "br-button secondary mt-3 mt-sm-0 mx-sm-3" %>
      <%= f.submit 'Salvar', class: "br-button primary mt-3 mt-sm-0 mx-sm-3" %>
    </div>
  <% end %>
</div>

app/views/pages/edit.html.erb
<div class="container">
  <div class="row justify-content-center mt-3">
    <div class="col col-lg-10 col-xl-8">
      <div class="row header-space">
        <h1><span class="blue-word">Editar</span> Cadastro</h1>
      </div>
      <div class="row header-text">
        <p><strong><%= @user.full_name %></strong>, aqui você pode editar seu cadastro.</p>
      </div>
      <%= render partial: 'form' %>
    </div>
  </div>
</div>

app/views/pages/index.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col col-lg-10 col-xl-8">
      <div class="row header-space">
        <h1><span class="blue-word">Seu</span> Sistema de Requisição</h1>
      </div>
      <div class="row header-text">
        <% if current_user.role.eql?("citizen") %>
          <p>Olá <strong> <%= current_user.full_name %>. </strong> Aqui é o espaço para gerenciar seu perfil e suas solicitações ao Inmetro</p>
        <% else %>
          <p>Olá <strong> <%= current_user.full_name %>. </strong> Aqui é o espaço para gerenciar seu perfil e as solicitações recebidas pelo seu Órgão.</p>
        <% end %>
      </div>
      <div class="row mt-1 px-sm-10xh">
        <div class="col mr-3">
          <%= link_to page_path(current_user), :class => "requests-link" do %>
            <div>
              <i class="bi bi-person-square"></i>
              <p class="text-center">Perfil</p>
            </div>
          <% end %>
        </div>
        <div class="col mr-3">
          <%= link_to requests_path, :class => "requests-link" do %>
            <div>
              <i class="bi bi-receipt"></i>
              <p class="text-center">Solicitações</p>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pages/show.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col col-lg-10 col-xl-8">
      <div class="row header-space">
        <h1><span class="blue-word">Seu</span> Cadastro</h1>
      </div>
      <div class="row header-text">
        <p> Aqui você pode editar os dados do seu cadastro.</p>
      </div>
      <hr class="solid">
      <div class="header-text">
        <label>CPF</label>
        <label class="cpf"><%= @user.cpf %></label>
        <label>Nome</label>
        <label class="input"><%= @user.full_name %></label>
        <label>E-mail</label>
        <label class="input"><%= @user.email %></label>
        <label>Telefone</label>
        <label class="input"><%= @user.phone_number %></label>
        <label>Endereço</label>
        <label class="input"><%= @user.address %></label>
      </div>
      <div class="row justify-content-end">
        <%= link_to 'Voltar', pages_path, class: "br-button secondary mt-3 mt-sm-0" %>
        <%= link_to 'Editar', edit_page_path(@user), class: "br-button primary mt-3 mt-sm-0 mx-sm-3" %>
      </div>
    </div>
  </div>
</div>

app/views/requests/_form.html.erb
<div class='container'>
  <%# Disable some input field if the current user is a tech %>
  <% is_disabled = current_user.role.eql?("tech") %>
  <%= simple_form_for(@request) do |f| %>
    <%= f.input :instrument, disabled: is_disabled, prompt: "Selecione o instrumento", label: "Instrumento", collection: Request::INSTRUMENTS, input_html: { class: "fit-content"} %>
    <%= f.input :service, disabled: is_disabled, prompt: "Selecione o serviço", label: "Serviço", collection: Request::SERVICES, input_html: { class: "fit-content"} %>
    <%= f.input :location, disabled: is_disabled, prompt: "Selecione o local", label: "Local", collection: Request::STATES, input_html: { class: "fit-content"} %>
    <%= f.input :description, disabled: is_disabled, label: "Descrição" %>
    <% unless @request.status.eql?('Aberta') || current_user.role.eql?("citizen") %>
      <%= f.input :report, label: "Relatório" %>
      <%= f.input :status, collection: Request::STATUS, input_html: { class: "fit-content"} %>
    <% end %>

    <div class="d-flex justify-content-end mb-3">
      <%= link_to 'Voltar', requests_path, class: "br-button secondary mt-3 mt-sm-0 mx-sm-3" %>
      <%= f.submit 'Enviar', class: "br-button primary mt-3 mt-sm-0 mx-sm-3" %>
    </div>
  <% end %>
</div>

app/views/requests/edit.html.erb
<div class="container">
  <div class="row justify-content-center mt-3">
    <div class="col col-lg-10 col-xl-8">
      <div class="row header-space">
        <h1><span class="blue-word">Editar</span> Requisição</h1>
      </div>
      <div class="row header-text">
        <p><strong><%= current_user.full_name %></strong>, aqui você pode editar solicitações abertas.</p>
      </div>
      <%= render partial: 'form' %>
    </div>
  </div>
</div>

app/views/requests/index.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col col-lg-10 col-xl-8">
      <div class="row header-space">
        <h1><span class="blue-word">Sua</span> Lista de Requisições</h1>
      </div>
      <div class="row header-text">
        <% if current_user.role.eql?("citizen") %>
          <p><strong> <%= current_user.full_name %>, </strong> aqui é o espaço para acompanhar suas solicitações ao Inmetro</p>
        <% else %>
          <p><strong> <%= current_user.full_name %>, </strong> aqui é o espaço para acompanhar as solicitações recebidas pelo seu Órgão.</p>
        <% end %>
      </div>

      <div class="col-sm-12 col-md-10 col-lg-8">
        <div class="row">
          <div class="br-card">
            <div id="orders" class="card-content">
              <ul class="list-group">
              <% @requests.each do |request| %>
                <li id="order-box" class="list-group-item" >
                <div id="card-head" class="card-header"><strong>Requisição nº:</strong>&nbsp<%= "%05d" % request.id %></div>
                  <div id="card-content-box" class="card-content">
                    <div id="card-content-item" class="card-content">
                      <div><strong>Instrumento:</strong>&nbsp<%= request.instrument %></div>
                    </div>
                    <div id="card-content-item" class="card-content">
                    <% if request.status == 'Realizada' %>
                    <div><strong>Status:</strong>&nbsp<a style="color:green"><%= request.status %></a></div>
                    <% elsif request.status == 'Em andamento' %>
                    <div><strong>Status:</strong>&nbsp<a style="color:red"><%= request.status %></a></div>
                    <% else %>
                    <div><strong>Status:</strong>&nbsp<a style="color:blue"><%= request.status %></a></div>
                    <% end %>
                    </div>
                  </div>
                <div id="card-foot" class="card-footer">
                  <div id="icon-btn" class="d-flex">
                    <div class="br-button inverted mt-3 mt-sm-0 ml-sm-3" type="button" aria-label="Ícone ilustrativo">
                      <span>
                      <%= link_to request_path(request) do %>
                        <i class="fas fa-edit"></i>
                      <% end %>
                      </span>
                    </div>
                  </div>
                </div>
                </li>
              <% end %>
              </ul>
            </div>
          </div>
        </div>
      </div>
      <div class="row justify-content-end">
        <%= link_to 'Voltar', pages_path, class: "br-button secondary mt-3 mt-sm-0" %>
        <% if current_user.role.eql?("citizen") %>
          <%= link_to 'Criar Requisição', new_request_path, class: "br-button primary mt-3 mt-sm-0 mx-sm-3" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/requests/index_manager.html.erb
<div class="container">
  <div class="br-table" data-search="data-search" data-collapse="data-collapse">
    <!-- Header da Tabela -->
    <div class="table-header">
      <div class="row header-space justify-content-center">
        <h1> Lista de Requisições</h1>
      </div>
      <div class="row header-text justify-content-center">
        <p><strong> <%= current_user.full_name %>, </strong> este é o espaço para acompanhar as solicitações recebidas pelo Inmetro.</p>
      </div>
      <%# <h1 class = "d-flex justify-content-center">Visão das Requisições</h1> %>

      <!-- Barra de Título -->
      <div class="top-bar">
        <!-- Título da tabela -->
        <div class="table-title">Lista das Requisições</div>
        <!-- Ativador de opções -->
        <div class="actions-trigger text-nowrap">
          <button class="br-button circle" type="button" title="Ver mais opções" data-toggle="dropdown" data-target="id-target" aria-controls="id-target" aria-expanded="false" data-visible="false">
            <i class="fas fa-filter" aria-hidden="true"></i>
          </button>
          <div class="br-list" id="id-target" aria-hidden="true" hidden>
            <%= link_to 'Abertas', requests_path(query: "Aberta"), class: "br-item text-decoration-none", turbolinks: false %>
            <%= link_to 'Em andamento', requests_path(query: "Em andamento"), class: "br-item text-decoration-none", turbolinks: false %>
            <%= link_to 'Realizadas', requests_path(query: "Realizada"), class: "br-item text-decoration-none", turbolinks: false %>
            <!--
            <%= link_to 'Todas', user_root_path, class: "br-item text-decoration-none", turbolinks: false %>
            -->
          </div>
        </div>

        <!-- Ativador de busca -->
        <div class="search-trigger">
          <button class="br-button circle" type="button" data-toggle="search" aria-label="Iniciar busca">
            <i class="fas fa-search" aria-hidden="true"></i>
          </button>
        </div>
      </div>

      <!-- Barra de Busca -->
      <div class="search-bar">
        <%= form_tag requests_path, class: "br-input", method: :get do %>
          <%= text_field_tag :query, params[:query], id: "table-searchbox-85957",
            class: "form-control",
            placeholder: "Buscar termo na descrição da requisição"
          %>
          <%= button_tag :submit, class: "br-button circle" do %>
            <i class="fas fa-search" aria-hidden="true"></i>
          <% end %>
        <% end %>
        <button class="br-button circle inverted" type="button" data-dismiss="search" aria-label="Encerrar busca">
          <i class="fas fa-times" aria-hidden="true"></i>
        </button>
      </div>
    </div>

    <table>
      <caption>Requests</caption>
      <thead>
        <tr>
          <th scope="col">Número</th>
          <th scope="col">Equipamento</th>
          <th scope="col">Serviço</th>
          <th scope="col">Status</th>
          <th scope="col">Criada em</th>
          <th scope="col">Atualizada em</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @requests.each do |request| %>
          <tr>
            <td>
              <%= "%05d" % request.id %>
            </td>
            <td>
              <%#= link_to request.instrument, request_path(request) %>
              <%= request.instrument %>
            </td>
            <td>
              <%= request.service %>
            </td>
            <td>
              <%= request.status %>
            </td>
            <td>
              <%= "%02d" % request.created_at.day %>/<%= "%02d" % request.created_at.month %>/<%= request.created_at.year %>
              <%= "%02d" % request.created_at.hour %>:<%= "%02d" % request.created_at.min %>
            </td>
            <td>
              <%= "%02d" % request.updated_at.day %>/<%= "%02d" % request.updated_at.month %>/<%= request.updated_at.year %>
              <%= "%02d" % request.updated_at.hour %>:<%= "%02d" % request.updated_at.min %>
            </td>
            <td>
              <%= link_to request_path(request) do %>
                <div>
                  <i class="fas fa-eye"></i>
                </div>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <!-- Rodapé da Tabela -->
    <div class="table-footer">
      <br>
      <!--
      <p><%= link_to 'Retornar para a página inicial', root_path, class: "br-button" %></p>
      -->
    </div>
  </div>
</div>

app/views/requests/new.html.erb
<div class="container">
  <div class="row justify-content-center mt-3">
    <div class="col col-lg-10 col-xl-8">
      <div class="row header-space">
        <h1><span class="blue-word">Criar</span> Requisição</h1>
      </div>
      <div class="row header-text">
        <p><strong><%= current_user.full_name %></strong>, aqui você pode criar uma nova solicitação ao Inmetro</p>
      </div>
      <%= render partial: 'form' %>
    </div>
  </div>
</div>

app/views/requests/show.html.erb
<div class="container">
  <div class="row justify-content-center mt-4">
    <div class="col col-lg-10 col-xl-8">
      <div class="px-sm-3 br-card">
        <div class="card-header bg-white">
          <div class="row header-space mt-0 mb-1">
            <h1><span class="blue-word">Detalhes da </span> Requisição n° <strong><%= @request.id %></strong> </h1>
          </div>
          <div class="row header-text">
            <p><strong> <%= current_user.full_name %></strong>, aqui você visualiza os detalhes da requisição.</p>
          </div>
        </div>

        <div class="card-content">
          <% unless current_user.role.eql?("citizen") %>
            <div class="row header-text">
              <h4><strong>Dados do requerente</strong></h4>
            </div>
            <dl class="row">
              <dt class="col-md-4 py-2"><span class="detail-type">Nome Completo:</span></dt>
              <dd class="col-md-8 pt-2 mb-0"><span class="detail-desc"><%= @request.citizen.full_name %></span></dd>

              <dt class="col-md-4 py-2"><span class="detail-type">E-mail:</span></dt>
              <dd class="col-md-8 pt-2 mb-0"><span class="detail-desc"><%= @request.citizen.email %></span></dd>

              <dt class="col-md-4 py-2"><span class="detail-type">Tel:</span></dt>
              <dd class="col-md-8 pt-2 mb-0"><span class="detail-desc"><%= @request.citizen.phone_number %></span></dd>

              <dt class="col-md-4 py-2"><span class="detail-type">CPF:</span></dt>
              <dd class="col-md-8 pt-2 mb-0"><span class="detail-desc"><%= @request.citizen.cpf %></span></dd>
            </dl>
            <hr class="solid">
          <% end %>
          <div class="row header-text">
            <h4><strong>Dados da solicitação</strong></h4>
          </div>
          <dl class="row">
            <dt class="col-md-4 py-2"><span class="detail-type">Instrumento:</span></dt>
            <dd class="col-md-8 pt-2 mb-0"><span class="detail-desc"><%= @request.instrument %></span></dd>

            <dt class="col-md-4 py-2"><span class="detail-type">Serviço:</span></dt>
            <dd class="col-md-8 pt-2 mb-0"><span class="detail-desc"><%= @request.service %></span></dd>

            <dt class="col-md-4 py-2"><span class="detail-type">Localização:</span></dt>
            <dd class="col-md-8 pt-2 mb-0"><span class="detail-desc"><%= @request.location %></span></dd>

            <dt class="col-md-4 py-2"><span class="detail-type">Data da Solicitação:</span></dt>
            <dd class="col-md-8 pt-2 mb-0"><span class="detail-desc"><%= @request.created_at.to_datetime.to_formatted_s(:long) %></span></dd>

            <dt class="col-md-4 py-2"><span class="detail-type">Status:</span></dt>
            <dd class="col-md-8 pt-2 mb-0"><span class="detail-desc"><%= @request.status %></span></dd>

            <dt class="col-md-4 py-2"><span class="detail-type">Descrição:</dt>
            <dd class="col-md-8 pt-2 mb-0"><span class="detail-desc"><%= @request.description %></span></dd>
            <% unless @request.status.eql?('Aberta') %>
              <dt class="col-md-4 py-2"><span class="detail-type">Relatório:</dt>
              <dd class="col-md-8 pt-2 mb-0"><span class="detail-desc"><%= @request.report %></span></dd>
              <% unless current_user.role.eql?("citizen") %>
                <dt class="col-md-4 py-2"><span class="detail-type">Técnico Designado:</span></dt>
                <dd class="col-md-8 pt-2 mb-0"><span class="detail-desc"><%= @request.tech.full_name %></span></dd>
              <% end %>
            <% end %>
          </dl>
        </div>
        <div class="card-footer bg-white p-3">
          <div class="row justify-content-end">
            <%= link_to 'Voltar', requests_path, class: "br-button secondary mt-3 mt-sm-0 mx-sm-3" %>
            <% case @request.status %>
              <% when "Aberta" %>
                <% case current_user.role %>
                  <% when "tech" %>
                    <%= link_to 'Atender', "#", class: "br-button primary mt-3 mt-sm-0 mx-sm-3", data: { toggle:"modal", target:"#staticBackdrop"} %>
                  <% when "citizen" %>
                    <%= link_to 'Editar', edit_request_path(@request), class: "br-button primary mt-3 mt-sm-0 mx-sm-3" %>
                <% end %>
              <% when "Em andamento" %>
                <% if current_user.role.eql?("tech") %>
                  <%= link_to 'Atualizar', edit_request_path(@request), class: "br-button primary mt-3 mt-sm-0 mx-sm-3" %>
                  <%= link_to 'Concluir', "#", class: "br-button primary mt-3 mt-sm-0 mx-sm-3", data: { toggle:"modal", target:"#staticBackdrop"} %>
                <% end %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<!-- Confirmation Modal -->
<div class="modal fade" id="staticBackdrop" data-backdrop="static" data-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <% if @request.status.eql?("Aberta") %>
          <h5 class="modal-title" id="staticBackdropLabel">Confirma sua atribuição ao serviço?</h5>
        <% else %>
          <h5 class="modal-title" id="staticBackdropLabel">Deseja concluir o serviço de verificação?</h5>
          <% end %>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-footer">
        <button type="button" class="br-button secondary" data-dismiss="modal">Voltar</button>
        <% if @request.status.eql?("Aberta") %>
          <%= link_to 'Sim', request_get_path(@request), method: :patch, class: "br-button primary" %>
        <% else %>
          <%= link_to 'Concluir', request_conclude_path(@request), method: :patch, class: "br-button primary" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="br-message success" role="alert">
    <div class="icon">
      <i class="fas fa-check-circle fa-lg" aria-hidden="true"></i>
    </div>
    <div class="content">
      <strong>Success. </strong><span><%= notice %></span>
    </div>
    <div class="close">
      <button class="br-button circle small" type="button" aria-label="Fechar"><i class="fas fa-times" aria-hidden="true"></i>
      </button>
    </div>
  </div>
<% end %>
<% if alert %>
  <div class="br-message warning" role="alert">
    <div class="icon">
      <i class="fas fa-exclamation-triangle fa-lg" aria-hidden="true"></i>
    </div>
    <div class="content">
      <strong>Atention. </strong><span><%= alert %></span>
    </div>
    <div class="close">
      <button class="br-button circle small" type="button" aria-label="Fechar"><i class="fas fa-times" aria-hidden="true"></i>
      </button>
    </div>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="br-footer">
    <div class="container-lg">
        <div class="govbr-logo">
          <img id="imgfoot" src="https://www.gov.br/++theme++padrao_govbr/img/govbr.png" alt="Gov Br" />
        </div>
           <div class="d-none d-sm-block">
            <div class="row align-items-end justify-content-between py-5">
              <div class="col social-network">
                <p class="text-up-01 text-extra-bold text-uppercase">Redes Sociais</p><a class="mr-2 fab fa-facebook" aria-hidden="true" href="https://www.facebook.com/governodobrasil"></a><a class="mr-3 fab fa-twitter" href="https://www.twitter.com/govbr"></a><a class="mr-3 fab fa-youtube" href="https://www.youtube.com/user/CanalPortalBrasil"></a><a class="mr-3 fab fa-instagram" href="https://www.instagram.com/governodobrasil"></a>
              </div>
            </div>
    </div>
    <div class="br-divider my-3"></div>
    <div class="container-lg">
        <div class="info">
            <div class="text-down-01 text-medium pb-3 text-center">
              Todo o conteúdo deste site está publicado sob a licença <a rel="license" href="https://creativecommons.org/licenses/by-nd/3.0/deed.pt_BR">Creative Commons Atribuição-SemDerivações 3.0 Não Adaptada</a>.
            </div>
        </div>
    </div>
</footer>